oliyh/martian

core/src/martian/swagger.cljc, core/test/martian/core_test.cljc
Martian can now be used when not all methods have an operationId, allowing
a more gradual introduction of Martian.
=> Filter methods without "operationId" from Martian instance.

README.md, core/src/martian/interceptors.cljc, core/test/martian/core_test.cljc
If no :martian.core/body parameter fallback to previous behaviour of
matching the schema name.
This change makes it easy to call methods with anonymous body schemas from
compojure-api which don't have deterministic names (body34512 etc).
=> Allow :martian.core/body to be used as the body schema name.

core/src/martian/core.cljc, core/src/martian/interceptors.cljc, core/test/martian/core_test.cljc
clojure.walk/keywordize-keys recursively clobbers map-like data
structures. This commit pulls out the call to keywordize-keys on the
params map into the `default-interceptors`. It retains the default
behaviour, but allows the user to optionally customize the behaviour.
Fix: #62
=> Extract keywordize-keys on params to interceptors

core/project.clj, core/src/martian/core.cljc, core/src/martian/schema.cljc, core/test/martian/schema_test.cljc
At the moment if you have a swagger property like this :
```clojure
{:Pet {:type  "object" :properties {}}}
```
The Plumatic schema that you get is:
```clojure
{:Pet {}}
```
This only allows an empty map as a posible value, which is quite restrictive and probably not very useful.
So, this PR changes the existing code so that if you have no explicit properties, it will produce the following to allow any value:
```clojure
{:Pet s/Any}
```
Happy to hear your thoughts on the approach and implementation. Relevant swagger docs for free form objects https://swagger.io/docs/specification/data-models/data-types#free-form.
Oliver
=> Handle free form objects

core/src/martian/schema.cljc, core/test/martian/schema_test.cljc
https://github.com/oliyh/martian/pull/76 introduced a bug on `enrich-handler`
More specifically on `parameter-keys`, since it is calling `s/explicit-schema-key` on `s/Any`
and giving this error
```
Bad explicit key: schema.core.AnythingSchema@3c6f0b88
```
Making the client unusable (for this swagger.json)
=> Fixes parameter-keys for open maps

cljs-http/src/martian/cljs_http.cljs, core/src/martian/interceptors.cljc, httpkit/src/martian/httpkit.clj, test/src/martian/test.cljc
Add intercetptors `remove-stack` which is equivalent to httpkit `go-async`.
=> Remove implicit httpkit dependency from martian test

clj-http-lite/.gitignore, clj-http-lite/project.clj, clj-http-lite/src/martian/clj_http_lite.clj, clj-http-lite/test/martian/clj_http_lite_test.clj
Hi,
This `clj-http-lite` based client is almost a complete copy of the `clj-http` client at least passes all tests and also works with [k8s-api](https://github.com/deas/k8s-api) (even with `watch`). Will be massaging pluggability in `k8s-api` a bit more and provide a PR over there soon. Still thinking about the `watch` implementation a bit, but I don't consider that related to `clj-http-lite` in `martian` scope.
=> Introduced clj-http-lite

core/src/martian/openapi.cljc, core/test-resources/openapi.json, core/test/martian/openapi_test.cljc
I'm keen to use Martian for a project at work, but the specs that I have to interact with are OpenAPI3 rather than Swagger2. I tried using a converted from OpenAPI to Swagger, but they ended up yielding sub-par schemas (lots of optional keys and maybes that didn't match required fields in the spec).
In order to make Martian fit our project better, I've put together this `martian.openapi` namespace. I'm not claiming that it's a full implementation of the spec, and in particular the "content types" thing was a bit hastily thrown together, but this seems to be sufficient for what I need, and I figured it might be helpful for someone else, too.
I took inspiration from the `martian.swagger` namespace, but no code is shared with it.
=> Add openapi->handlers functionality

core/src/martian/openapi.cljc, core/test-resources/openapi2.json, core/test/martian/openapi_test.cljc
Keywordizing broke the parameters for OpenAPI parsing. The test didn't have any parameters, so it wasn't spotted. Closes #93
=> OpenAPI parameters

.gitignore, clj-http-lite/src/martian/clj_http_lite.clj, clj-http/src/martian/clj_http.clj, cljs-http/src/martian/cljs_http.cljs, hato/src/martian/hato.clj, httpkit/src/martian/httpkit.clj
This allows to pass extra options to the http/get that does the fetching of the swagger file.
=> add way to pass extra options when fetching the swagger

clj-http-lite/project.clj, clj-http/project.clj, core/project.clj, hato/project.clj, httpkit/project.clj
Bump cheshire to latest release which includes this fix: 
https://github.com/dakrone/cheshire/commit/73daea7eba04ab214f38a9d3a1398329224f7c52
=> Bump cheshire and fix jackson CVE-2020-28491

clj-http-lite/src/martian/clj_http_lite.clj, clj-http-lite/test/martian/clj_http_lite_test.clj, clj-http/src/martian/clj_http.clj, clj-http/test/martian/clj_http_test.clj, cljs-http-promise/src/martian/cljs_http_promise.cljs, cljs-http-promise/test/martian/cljs_http_promise_test.cljs, cljs-http/src/martian/cljs_http.cljs, cljs-http/test/martian/cljs_http_test.cljs, core/project.clj, core/src/martian/openapi.cljc, hato/src/martian/hato.clj, hato/test/martian/hato_test.clj, httpkit/src/martian/httpkit.clj, httpkit/test/martian/httpkit_test.clj, test-common/martian/server_stub.clj, test-common/public/openapi-test.json
I believe this PR should address issue #116 .  At least for the CLJ clients.
Currently `openapi/base-url` picks the first server listed in the `servers` field.
To allow the selection of any server, I added the capability of providing a `:server-url` key in the `opts` parameter of `martian-http/bootstrap-openapi`.
I have made the changes to each CJ client and added tests for each of them.
I have not yet made the corresponding changes to the CLJS clients or added tests for them.
I am not sure how the tests for the CLJS clients are supposed to work. I ran `lein test` on the CLJ clients just fine.
Running `lein test` from the `cljs-http` directory results in
```
Syntax error (NoSuchMethodError) compiling at (figwheel/main.cljc:1:1).
'java.util.stream.Collector …
```
=> Add support for absolute OpenAPI server URLs

core/src/martian/openapi.cljc, core/test/martian/openapi_test.cljc
This partially addresses #145.
If a schema has no "type" key, and ONLY has a "properties" key, then
it is a valid schema and we can reasonably assume that the type is "object".
See https://github.com/OAI/OpenAPI-Specification/issues/1657
Excerpt:
A particularly common form of this is a schema that omits type, but specifies properties.
Strictly speaking, this does not mean that the value must be an object.
It means that if the value is an object, and it includes any of those properties,
the property values must conform to the corresponding property subschemas.
In reality, this construct almost always means that the user intends type: object,
and I think it would be reasonable for a code generator to assume this,
maybe with a validation: strict|lax config option to control that behavior.
=> Handle schemas with no type.

core/src/martian/schema.cljc, core/test-resources/swagger.json, core/test/martian/schema_test.cljc
These changes assist with using the Kubernetes API which makes use of date-time fields and has the concept of a int-or-string format. 
Without the int-or-string type - Martian gives a validation error when trying to use the ':port 8080' in a kubernetes readiness check complaining that a String is required. :port 8080 is a valid value as-is :port "https" and they have different meanings to Kubernetes.
I'm not sure if this specific use case makes sense for upstream and the tests for these enhancements could probably be expanded but I figured I'd submit this pull request just in case.
=> Support date-time and int-or-string string formats

core/src/martian/openapi.cljc, core/src/martian/schema.cljc, core/test-resources/kubernetes-openapi-v3-converted.yaml, core/test-resources/kubernetes-swagger-v2.json, core/test/martian/openapi_test.cljc, core/test/martian/swagger_test.cljc
This pull request fixes an issue encountered using the Kubernetes "Patch" API where Martian complains that the patch body parameter can't have any properties. This is because a patch reference in the body field is defined as follows:
"io.k8s.apimachinery.pkg.apis.meta.v1.Patch": {
"description": "Patch is provided to give a concrete name and type to the Kubernetes PATCH request body.",
"type": "object"
}
This "object" does not define any parameters or additionalParameters and _I think_ (based on my limited reading of the Swagger v2 and JSON schema specs that this means that the 'object' can have any parameters.
I've included a test case to detect this scenario and the code change does not impact any other Martian tests but I'm not yet 100% certain about this and am interested in whether …
=> Fix no object properties

core/src/martian/core.cljc, core/src/martian/openapi.cljc, core/test/martian/yaml_test.clj
When an operation is deprecated in the openapi spec this PR makes the `deprecated` field available when exploring the endpoint.
=> add support for the deprecated field on the operation

README.md
The note is from 2021-07-13, almost two years ago.
It makes it seem like the project is no longer active because old documentation, which is inaccurate. ;)
=> removing Clojars coordinates notice from README

core/src/martian/openapi.cljc, core/test/martian/openapi_test.cljc
Ref: Originating [issue](https://github.com/wkok/openai-clojure/issues/25)
When [spec instrumentation](https://clojure.org/guides/spec#_instrumentation_and_testing) is enabled, and bootstrapping a martian using an OpenAPI v3 definition containing no content-type declaration for the request (for example a GET), then spec validation fails for example:
Definition with no content-type declaration for the request:
```yaml
openapi: 3.0.0
info:
title: OpenAI API
description: APIs for sampling from and fine-tuning language models
version: '1.3.0'
servers:
- url: https://api.openai.com/v1
paths:
/models:
get:
operationId: listModels
summary: Lists the currently available models
responses:
"200":
description: OK
content:
application/json:
schema: {}
``` 
In a test namespace, enable spec …
=> Fixed spec validation failure when no content-type present for request

README.md
The Babashka http client also runs on the JVM and this marks it as such.
=> [doc] Mark babashka http client as JVM compatible

core/src/martian/openapi.cljc, core/src/martian/schema.cljc, core/src/martian/swagger.cljc, core/test/martian/schema_test.cljc, core/test/martian/swagger_test.cljc
As I commented in the issue
https://github.com/oliyh/martian/issues/195
This is not working for swagger, but it is for OpenAPI v3. I tried to refactor the code to use the same logic, adding tests for it.
=> Fix Reference Object usage on parameters for swagger spec

vcr/src/martian/vcr.cljc
=> Ensure graceful failure for implementation-specific objects that vcr writes but can't read back

vcr/src/martian/vcr.cljc, vcr/test/martian/vcr_test.cljc
References #181.
`remove-stack` prevents all further interceptors from running. It uses `terminate` under the hood. Critical difference: `terminate` just means we'd move to the second phase (`:leave`), ensuring things like e.g. response body encoding still happens.
=> Terminate the stack but don't remove the rest when using VCR

core/src/martian/interceptors.cljc, core/src/martian/schema.cljc, core/test/martian/core_test.cljc, core/test/martian/schema_test.cljc
This fixes up the issue with [Missing-key / disallowed key on path-params when setting defaults in query-schema #215](https://github.com/oliyh/martian/issues/215).
```clojure
(require
'[martian.core :as martian]
'[spec-tools.core :as st])
(def m (martian/bootstrap
"http://example.com"
[{:query-schema {:version (st/default s/Int 70)},
:path-schema  {:id s/Str}
:route-name   :test/route
:method       :get,
:path-parts   ["/part/" :id]}]
{:use-defaults? true}))
=> #'user/m
(martian/request-for m :test/route {:id "honestly-i-am-a-string"})
=> {:method :get, :url "http://example.com/part/honestly-i-am-a-string", :query-params {:version 70}}
(martian/request-for m :test/route {})
Execution error (ExceptionInfo) at schema-tools.coerce/coerce-or-error! (coerce.cljc:24).
Could not coerce value to …
```
=> Fix how default values interplay with map schemas coercion

README.md, core/src/martian/core.cljc, core/src/martian/interceptors.cljc, core/src/martian/schema.cljc, core/test/martian/schema_test.cljc
@oliyh Hello again, Oliver!
This PR addresses a proposal made in #220.
The main part is essentially non-breaking (passing things through existing `:opts` to override the `default-coercion-matcher`), but I've also made a few minor relevant improvements here and there — improved readability/maintainability, exposed some useful schema internals (private -> public), reused `schema-tools` fns, and reordered `core` ns imports.
Thanks for such a neat tool!
=> Support setting coercion matchers via Martian `:opts`

README.md, test/README.md, test/src/martian/test.cljc, test/test/martian/test_test.cljc
@oliyh Hi Oliver!
There are a few things in the `martian-test` module that I believe require a bit of a facelift.
Firstly, I'd like to [introduce a new testing facility — the `respond-with-contextual`](https://github.com/oliyh/martian/commit/ef832c6060f141530a84fd8b2916441e0c9e4c4d) — which is basically an extension of the existing `respond-with`/`respond-with-constant` fns, so these two are not synonymous any more (so I've carefully added this new feature in a backward-compatible way).
Secondly, I've [added a missing 'babashka.http-client' support](https://github.com/oliyh/martian/commit/873e13f181afa0adceac1833ea0146cf9c538edf) to the `martian.test`. This HTTP client is already supported by the main Martian lib, so it has to be covered here as well.
Finally, I've also improved on public …
=> Improve on test module

babashka-http-client/src/martian/babashka/http_client.clj, babashka-http-client/test/martian/babashka/http_client_test.clj, clj-http-lite/project.clj, clj-http-lite/src/martian/clj_http_lite.clj, clj-http-lite/test/martian/clj_http_lite_test.clj, clj-http/src/martian/clj_http.clj, clj-http/test/martian/clj_http_test.clj, cljs-http-promise/project.clj, cljs-http-promise/src/martian/cljs_http_promise.cljs, cljs-http-promise/test/martian/cljs_http_promise_test.cljs, cljs-http/project.clj, cljs-http/src/martian/cljs_http.cljs, cljs-http/test/martian/cljs_http_test.cljs, core/project.clj, core/src/martian/encoders.cljc, core/src/martian/encoding.cljc, core/src/martian/interceptors.cljc, core/src/martian/openapi.cljc, core/src/martian/utils.cljc, core/test/martian/encoding_test.cljc, core/test/martian/interceptors_test.cljc, hato/src/martian/hato.clj, hato/test/martian/hato_test.clj, httpkit/src/martian/httpkit.clj, httpkit/test/martian/httpkit_test.clj, test-common/martian/server_stub.clj, test-common/martian/test_utils.clj, test-common/public/openapi-coercions.json, test-common/public/openapi.json
**In Scope:**
- #232
- #234
- #233
- #189
- #58
- #237
- #236
**Notes:**
These all are closely related, and it's super hard to fix them individually while preserving logical completeness, correctness and some basic compatibility. For instance, when one fixes #232, everything else starts to fall apart because an encoder for a specific "Content-Type" now gets detected and the "two negatives make an affirmative" rule stops working for us! 😫 
That said, I decided to ship everything together, but in a gradual way (which someone may call "TDD").
First, I introduce a missing test coverage for all target HTTP clients and supported content types (and the `"*/*"` OpenAPI/Swagger response content special case). I also put a number of ToDo items in tests for all the issues I've found. Please, note …
=> Fix response coercion issues

README.md, core/src/martian/core.cljc, core/src/martian/interceptors.cljc, core/src/martian/spec.cljc, core/src/martian/swagger.cljc, test/src/martian/test.cljc
@oliyh Hi Oliver!
I came across another subtle issue (sorry!) in the current implementation of the Martian core module.
The original error — recently discovered in my own project, which uses Martian quite extensively — was rather cryptic:
```clojure
...
Caused by: java.lang.IllegalArgumentException: No implementation of method: :spec of protocol: #'schema.core/Schema found for class: nil
at clojure.core$_cache_protocol_fn.invokeStatic (core_deftype.clj:585)
clojure.core$_cache_protocol_fn.invoke (core_deftype.clj:577)
schema.core$eval6697$fn__6709$G__6686__6714.invoke (core.cljc:96)
martian.schema_tools$with_paths.invokeStatic (schema_tools.cljc:18)
martian.schema_tools$with_paths.invoke (schema_tools.cljc:9)
martian.schema_tools$key_seqs.invokeStatic (schema_tools.cljc:28) …
```
=> Handle invalid handlers properly

core/src/martian/core.cljc, test/test/martian/test_test.cljc
@oliyh Hi Oliver!
There was a small regression issue that somehow slipped under the radar. Luckily, it was introduced just recently, in #239, which has not yet been released.
The `request-for` function's interceptor chain became misordered/broken in the presence of a `respond-with-***` fn call.
This fixes the root cause and covers this case with a test.
Cheers,
Mark
=> Fix interceptors order in `request-for` chain

babashka-http-client/test/martian/babashka/http_client_test.clj, cljs-http-promise/test/martian/cljs_http_promise_test.cljs, cljs-http/test/martian/cljs_http_test.cljs, core/src/martian/interceptors.cljc, core/test/martian/interceptors_test.cljc
@oliyh Hi Oliver!
This PR updates the **supported content types for OpenAPI specs** with the default ones.
The `"text/plain"` and `"application/octet-stream"` are the [default mime types of the web](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/MIME_types#important_mime_types_for_web_developers).
These are de facto supported by each and every HTTP client, including the target ones.
Hence, no specific treatment needs to be added on the Martian's side to process these.
The PR addresses:
- the last bit of the issue #58, and
- combined with #240, it also reduces noise in logs (#214).
Hope that helps!
Cheers,
Mark
=> Add default content types
